import { StyleSheet, Platform, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    paddingTop: Platform.OS === 'ios' ? 56 : 32,
    paddingHorizontal: 24,
  },
  popup: {
    position: 'absolute',
    top: 40,
    left: 0,
    right: 0,
    marginHorizontal: 24,
    backgroundColor: '#A03A5E',
    padding: 16,
    borderRadius: 12,
    zIndex: 100,
    alignItems: 'center',
    elevation: 10,
  },
  popupText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  input: {
    borderWidth: 1,
    borderColor: '#CFCFD1',
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
    marginBottom: 12,
    backgroundColor: '#fff',
  },
  textArea: {
    height: 120,
    textAlignVertical: 'top',
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#A03A5E',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
    backgroundColor: '#fff',
  },
  checkboxChecked: {
    backgroundColor: '#A03A5E',
    borderColor: '#A03A5E',
  },
  checkboxLabel: {
    fontSize: 16,
    color: '#A03A5E',
    fontWeight: '500',
  },
  dropdown: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#CFCFD1',
    borderRadius: 12,
    marginBottom: 12,
    marginTop: -8,
    zIndex: 10,
    elevation: 4,
  },
  dropdownItem: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F2F2F2',
  },
  button: {
    marginTop: 'auto',
    backgroundColor: '#A03A5E',
    borderRadius: 16,
    paddingVertical: 18,
    alignItems: 'center',
    marginBottom: 24,
  },
  buttonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 17,
  },
  containerPerfil: {
    flex: 1,
    backgroundColor: '#fff',
    paddingTop: 48,
  },
  header: {
    fontSize: 20,
    fontWeight: 'bold',
    alignSelf: 'center',
    marginBottom: 24,
  },
  avatarContainer: {
    alignItems: 'center',
    marginBottom: 16,
  },
  avatar: {
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: '#C96A8C',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
    position: 'relative',
  },
  editIcon: {
    position: 'absolute',
    bottom: 8,
    right: 8,
    backgroundColor: '#A03A5E',
    borderRadius: 12,
    padding: 2,
    borderWidth: 2,
    borderColor: '#fff',
  },
  name: {
    fontSize: 22,
    fontWeight: 'bold',
    marginTop: 4,
  },
  username: {
    fontSize: 15,
    color: '#888',
    marginBottom: 8,
  },
  divider: {
    height: 1,
    backgroundColor: '#E6E6E6',
    marginHorizontal: 24,
    marginVertical: 16,
  },
  options: {
    marginHorizontal: 8,
  },
  optionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 18,
    paddingHorizontal: 16,
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: '#F2F2F2',
  },
  optionText: {
    fontSize: 16,
    color: '#222',
  },
  loginButton: {
    marginTop: 32,
    marginHorizontal: 24,
    backgroundColor: '#A03A5E',
    borderRadius: 8,
    paddingVertical: 14,
    alignItems: 'center',
  },
  loginButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalContent: {
    backgroundColor: '#fff',
    borderRadius: 24,
    padding: 24,
    width: width * 0.9,
    maxHeight: '80%',
    alignItems: 'stretch',
    elevation: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    alignSelf: 'center',
    marginBottom: 16,
    color: '#333',
  },
  modalDescription: {
    marginBottom: 10,
    textAlign: 'justify',
    fontSize: 16,
    color: '#555',
  },
  modalLocation: {
    marginBottom: 5,
    fontSize: 14,
    color: '#777',
    fontStyle: 'italic',
  },
  modalDate: {
    marginTop: 10,
    fontSize: 12,
    color: '#888',
    textAlign: 'right',
  },
  closeModalButton: {
    backgroundColor: '#A03A5E',
    borderRadius: 16,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 20,
    width: '100%',
  },
  closeModalButtonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 16,
  },
  errorText: {
    color: '#A03A5E',
    fontSize: 14,
    marginBottom: 4,
    alignSelf: 'center',
  },
  modalButton: {
    flex: 1,
    borderRadius: 24,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  logoutModalContent: {
    backgroundColor: '#fff',
    borderRadius: 24,
    padding: 24,
    width: 360,
    alignItems: 'stretch',
    elevation: 6,
  },
  logoutTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    alignSelf: 'center',
    marginBottom: 8,
  },
  logoutText: {
    fontSize: 18,
    color: '#7A7A7A',
    textAlign: 'center',
    marginBottom: 8,
    marginTop: 4,
  },
  cancelButton: {
    backgroundColor: '#fff',
    borderWidth: 2,
    borderColor: '#A03A5E',
  },
  privacyModalContent: {
    backgroundColor: '#fff',
    borderRadius: 24,
    padding: 24,
    width: 360,
    alignItems: 'stretch',
    elevation: 6,
  },
  privacyText: {
    fontSize: 16,
    color: '#444',
    marginBottom: 10,
    lineHeight: 22,
  },
  feedCardSection: {
    marginBottom: 20,
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  feedCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  feedCardTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
  },
  seeMoreButton: {
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  seeMoreButtonText: {
    color: '#A03A5E',
    fontWeight: '500',
    fontSize: 16,
  },
  itemCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F2F2F2',
  },

  lastItemCard: {
    borderBottomWidth: 0,
  },
  itemInfo: {
    flex: 1,
    marginRight: 10,
  },
  itemTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
  },
  itemLocation: {
    fontSize: 14,
    color: '#666',
    marginTop: 2,
  },
  itemArrow: {
    marginLeft: 16,
  },

  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },

  modalView: {
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    maxHeight: '80%',
    width: width * 0.9,
  },

  modalLabel: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    marginTop: 10,
    marginBottom: 2,
  },
  modalText: {
    fontSize: 16,
    color: '#555',
    marginBottom: 5,
    textAlign: 'justify',
  },
  modalTextDetail: {
    fontSize: 14,
    color: '#777',
    fontStyle: 'italic',
    marginBottom: 5,
  },

  denunciasListContainer: {
    backgroundColor: '#fff',
    borderRadius: 8,
    marginTop: 10,
    paddingHorizontal: 0,
    paddingTop: 0,
    paddingBottom: 0,
  },
  noDenunciasText: {
    textAlign: 'center',
    fontStyle: 'italic',
    color: '#888',
    paddingVertical: 15,
  },
});

export default styles;
